---
{{- if and
  .Values.grafana.enabled
  .Values.istio.grafana.enabled
}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.istio.grafana.ruleName }} 
spec:
  host: {{ .Values.istio.grafana.host }}
  subsets:
  - name: v1
    labels:
      version: v1
{{- end }}
---
{{- if and
  (index .Values "elastic-eck-stk" "enabled")
  (index .Values "elastic-eck-stk" "eck-kibana" "enabled")
  .Values.istio.kibana.enabled
}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.istio.kibana.ruleName }} 
spec:
  host: {{ .Values.istio.kibana.host }}
  subsets:
  - name: v1
    labels:
      version: v1
{{- end }}

