---
{{- if .Values.istio.kibana.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.istio.kibana.ruleName }} 
  namespace: {{ .Values.istio.kibana.namespace }}
spec:
  host: {{ .Values.istio.kibana.host }}
  subsets:
  - name: v1
    labels:
      version: v1
{{- end }}

