---
{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.admin.existingSecret }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  "{{ .Values.grafana.admin.userKey }}": {{ .Values.grafana.username | b64enc }}
  "{{ .Values.grafana.admin.passwordKey }}": {{ .Values.grafana.password | b64enc }}
{{- end }}

