---
{{- if
  (index .Values "global" "tags" "jaeger-components")
  .Values.grafana.enabled
}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-user
type: Opaque
data:
  username: {{ .Values.grafana.username | b64enc }}
  password: {{ .Values.grafana.password | b64enc }}
{{- end }}

