---
{{- if .Values.istio.kibana.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.kibana.virtualServiceName }}
  namespace: {{ .Values.istio.kibana.namespace }}
spec:
  {{- with.Values.istio.gateways }}
  gateways:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with.Values.istio.host }}
  hosts:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.kibana.path }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .values.istio.kibana.host }}
        port:
          number: {{ .values.istio.kibana.port }}
        subset: v1
{{- end }}

