---
{{- if and
  .Values.grafana.enabled
  .Values.istio.grafana.enabled
}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.grafana.virtualServiceName }}
  namespace: {{ include "observability.namespace" . }}
spec:
  {{- with .Values.istio.gateway }}
  {{- if . }}
  gateways:
  - {{ . }}  
  {{- end }}
  {{- end }}
  {{- with .Values.istio.destinationHost }}
  {{- if . }}
  hosts:
  - {{ . }}  
  {{- end }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.grafana.path }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.istio.grafana.host }}
        port:
          number: {{ .Values.istio.grafana.port }}
        subset: v1
{{- end }}
---
{{- if and
  (index .Values "elastic-eck-stk" "enabled")
  (index .Values "elastic-eck-stk" "eck-kibana" "enabled")
  .Values.istio.kibana.enabled
}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.kibana.virtualServiceName }}
  namespace: {{ include "observability.namespace" . }}
spec:
  {{- with .Values.istio.gateway }}
  {{- if . }}
  gateways:
  - {{ . }}  
  {{- end }}
  {{- end }}
  {{- with .Values.istio.destinationHost }}
  {{- if . }}
  hosts:
  - {{ . }}  
  {{- end }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.kibana.path }}
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.istio.kibana.host }}
        port:
          number: {{ .Values.istio.kibana.port }}
        subset: v1
{{- end }}

