---
{{- if .Values.istio.kibana.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kibana-rule
  namespace: observability
spec:
  gateways: {{ .Values.istio.gateways | toYaml | nindent 2 }}
  hosts: {{ .Values.istio.kibana.hosts | toYaml | nindent 2 }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.kibana.path }}
    rewrite:
      uri: /
    route:
    - destination:
        host: kibana-kb-http.observability.svc.cluster.local
        port:
          number: 5601
        subset: v1
{{- end }}

